/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
    docs: [
        {
            type: "category",
            label: "introduction",
            items: [
                "introduction/what-is-exabits",
                "introduction/computing-power-at-our-fingertips-the-cornerstone-of-an-intelligent-society",
            ],
        },
        {
            type: "category",
            label: "background",
            items: [
                "background/why-decentralized-computing-matters",
                "background/why-decentralized-computing-can-lower-the-cost-of-ai",
                "background/what-is-the-difference-between-computing-and-storage",
            ],
        },
        {
            type: "category",
            label: "usecase",
            items: ["usecase/ai-is-running-out-of-computing-power"],
        },
        {
            type: "category",
            label: "technology",
            items: [
                "technology/a-mutual-computing-network-stack",
                "technology/dico-a-decentralized-computing-protocol",
            ],
        },
        {
            type: "category",
            label: "blog",
            items: [
                "blog/decentralized-cloud-computing-project-exabits-incubated-by-harvard-innovation-labs",
            ],
        },
    ],
};

module.exports = sidebars;
